spring.h2.console.enabled: true
spring:
    # DB ??
    datasource:
    # ??? H2 DB? ?? URL
        url: jdbc:h2:mem:springcoredb
        username: sa
        password:
        # ??? ?? ????
        driver-class-name: org.h2.Driver
    jpa:
        # JPA? ???? SQL? ? ? ??.
        show-sql: true
        # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none
        # ????? ??? create? ????
        # ???? none ?? ???. create?? ??? ???? ?? ??????.
        hibernate:
            ddl-auto: create
        # ??? sql ??? ??
        properties:
            hibernate.format_sql: true
    # ?? ?? ? ?? always
    output:
        ansi:
            enabled: always
# ???? ??? ?? trace
logging:
    level:
        org.hibernate.type: trace